### ISSUE TITLE
Feature Request: History Tab Filter

### ISSUE THREAD

**Issue by robrinker** [squatsandsciencelabs/OpenBarbell-V3#1]
It would be awesome if there was an option on the History tab in the app to filter based on Exercise and possibly also on total number of reps in a set.

I typically use singles at an 8 RPE to calibrate my working sets. I find that if my velocity on a single has increased since the last time I performed an exercise, then I can safely add more weight to working sets of RPE 9, 9.5, and 10 without missing reps. To do this now, I have to "tag" the number of total reps in the set, export my data to drive, open in Sheets, then filter on "Tags" and "Exercise" to find the data I'm looking for. 

This can get a bit awkward in the gym in the middle of a training session.

Thanks for considering my request!

**Comment by squatsandscience** [comment]
This is here! It's actually in the latest build. @robrinker
